### ISSUE TITLE
Warning: Native component for "RNBarcodeScannerView" does not exist

### ISSUE THREAD

**Issue by fgrs** [ideacreation/react-native-barcodescanner#45]
this is similar if not the same to #38 but still applies to my project, tried **rnpm link** it says **Android module react-native-barcodescanner is already linked** also I removed android folder and run react-native run-android, still getting this error

`react: 15.2.1, react-native: 0.30.0, react-native-barcodescanner: 3.0.1`

**Comment by fgrs** [comment]
looks like MainApplication.java is not getting updated after **rnpm link**

**Comment by andreaskeller** [comment]
@fgrs did you solve your problem? maybe you are using an older version of `rnpm`? with recent react-native versions you can also just run `react-native link` instead of `rnpm link`.

**Comment by jmdelatorre** [comment]
Hi @fgrs where you able to fix this problem?

**Comment by henninghall** [comment]
@jmdelatorre as @fgrs says the problem seems to be in MainApplication.java. I did a [manual linking](https://github.com/ideacreation/react-native-barcodescanner#manual-linking) which meant adding               "new BarcodeScannerPackage()" to MainApplication.java and the problem was fixed.

**Comment by teemobk** [comment]
Hi @jmdelatorre @fgrs @andreaskeller @henninghall : I did [manual linking](https://github.com/ideacreation/react-native-barcodescanner#manual-linking), but still getting this error:
**Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead.
Warning: Native component for "RNBarcodeScannerView" does not exist**
Where you able to fix this problem? Thanks

**Comment by andreaskeller** [comment]
I'm sorry but this component is no longer maintained. Try [react-native-camera](https://github.com/lwansbrough/react-native-camera) as a replacement.
